// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.Database;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20241013211532_seed ninjas and equipment")]
    partial class seedninjasandequipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b9838d2-66a1-4323-99ff-9527b2461430"),
                            Agility = 10,
                            Category = 0,
                            Intelligence = 20,
                            Name = "Steel Helmet",
                            Price = 50,
                            Strength = 30
                        },
                        new
                        {
                            Id = new Guid("b66905e2-bea0-4b84-ae8b-85f58d0c93ac"),
                            Agility = 50,
                            Category = 0,
                            Intelligence = -50,
                            Name = "Leather Hood",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("589eacbb-9197-4def-b0d2-58e511878d97"),
                            Agility = 30,
                            Category = 0,
                            Intelligence = 150,
                            Name = "Mystic Crown",
                            Price = 100,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("32d87f35-58b8-4de0-beba-6154ab59529a"),
                            Agility = -10,
                            Category = 1,
                            Intelligence = 40,
                            Name = "Chainmail Armor",
                            Price = 120,
                            Strength = 80
                        },
                        new
                        {
                            Id = new Guid("9a8254fd-aeec-415c-b3a2-cc0bade31649"),
                            Agility = 70,
                            Category = 1,
                            Intelligence = 100,
                            Name = "Silk Robe",
                            Price = 80,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("ab3edc55-c09b-4bef-af4c-3c5a7224be9f"),
                            Agility = 90,
                            Category = 1,
                            Intelligence = -30,
                            Name = "Battle Vest",
                            Price = 60,
                            Strength = 60
                        },
                        new
                        {
                            Id = new Guid("68420241-7871-412a-b490-7f065ceed8d4"),
                            Agility = 20,
                            Category = 2,
                            Intelligence = 10,
                            Name = "Iron Gauntlets",
                            Price = 40,
                            Strength = 50
                        },
                        new
                        {
                            Id = new Guid("532f00f2-2388-4446-880b-1d64ba067995"),
                            Agility = 100,
                            Category = 2,
                            Intelligence = 5,
                            Name = "Leather Gloves",
                            Price = 25,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("560daca4-cb75-4e44-8112-d1db5d6d501d"),
                            Agility = 60,
                            Category = 2,
                            Intelligence = 175,
                            Name = "Enchanted Gloves",
                            Price = 90,
                            Strength = 8
                        },
                        new
                        {
                            Id = new Guid("9d1ddb4d-5b34-4e6b-b859-4c2671048906"),
                            Agility = 30,
                            Category = 3,
                            Intelligence = -100,
                            Name = "Steel Boots",
                            Price = 50,
                            Strength = 40
                        },
                        new
                        {
                            Id = new Guid("c458dd35-be5b-47a1-9683-29adc301b67f"),
                            Agility = 200,
                            Category = 3,
                            Intelligence = 30,
                            Name = "Ninja Sandals",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("bff935bd-e0a6-4ba8-9e21-1e7793ddfb31"),
                            Agility = 250,
                            Category = 3,
                            Intelligence = 80,
                            Name = "Mage Slippers",
                            Price = 70,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("5b010d11-b8b1-4d05-9fcf-329ceb0f8e67"),
                            Agility = 50,
                            Category = 4,
                            Intelligence = -20,
                            Name = "Ring of Strength",
                            Price = 200,
                            Strength = 100
                        },
                        new
                        {
                            Id = new Guid("4f5b5e32-46e0-4961-9c3a-fc7669d998bc"),
                            Agility = -25,
                            Category = 4,
                            Intelligence = 200,
                            Name = "Ring of Intelligence",
                            Price = 180,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("294c2784-de64-45c2-ab94-157d6963a2d3"),
                            Agility = 300,
                            Category = 4,
                            Intelligence = -50,
                            Name = "Ring of Agility",
                            Price = 160,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("b1ff3b66-bf82-4061-822a-a92186e72b63"),
                            Agility = 40,
                            Category = 5,
                            Intelligence = 60,
                            Name = "Amulet of Power",
                            Price = 250,
                            Strength = 90
                        },
                        new
                        {
                            Id = new Guid("7f54efe2-4208-4bcc-82e7-537aab5e5878"),
                            Agility = 75,
                            Category = 5,
                            Intelligence = 180,
                            Name = "Mystic Necklace",
                            Price = 220,
                            Strength = 20
                        },
                        new
                        {
                            Id = new Guid("f41a43db-e374-4c1e-89c4-f78416ef03b4"),
                            Agility = 280,
                            Category = 5,
                            Intelligence = 70,
                            Name = "Pendant of Speed",
                            Price = 190,
                            Strength = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b06a4db7-6db3-454c-a593-7d140dad4d90"),
                            Gold = 2000,
                            Name = "Shadowstrike Kenji"
                        },
                        new
                        {
                            Id = new Guid("3090b339-c693-4c49-b7e1-6509456c987a"),
                            Gold = 500,
                            Name = "Crimson Whisper"
                        },
                        new
                        {
                            Id = new Guid("fea7194f-a9f9-43fa-b811-1c60de5f451b"),
                            Gold = 2000,
                            Name = "Nightwind Taro"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
