// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.Database;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20241031190000_updatedOrderWithFK")]
    partial class updatedOrderWithFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8337871-8051-48a7-8dc0-6ac15d7fbfd1"),
                            Agility = 10,
                            Category = 0,
                            Intelligence = 20,
                            Name = "Steel Helmet",
                            Price = 50,
                            Strength = 30
                        },
                        new
                        {
                            Id = new Guid("5c9849f7-3ea8-4acb-8903-c97f92d760b9"),
                            Agility = 50,
                            Category = 0,
                            Intelligence = -50,
                            Name = "Leather Hood",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("4a447a9a-b435-412b-847a-0f4188cc8356"),
                            Agility = 30,
                            Category = 0,
                            Intelligence = 150,
                            Name = "Mystic Crown",
                            Price = 100,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("890c908d-345b-4604-97b7-f36b627dce1c"),
                            Agility = -10,
                            Category = 1,
                            Intelligence = 40,
                            Name = "Chainmail Armor",
                            Price = 120,
                            Strength = 80
                        },
                        new
                        {
                            Id = new Guid("c61006de-2573-415d-abac-c8a1778224e0"),
                            Agility = 70,
                            Category = 1,
                            Intelligence = 100,
                            Name = "Silk Robe",
                            Price = 80,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("8a0cd42b-1373-4830-985e-635e6dba6e5c"),
                            Agility = 90,
                            Category = 1,
                            Intelligence = -30,
                            Name = "Battle Vest",
                            Price = 60,
                            Strength = 60
                        },
                        new
                        {
                            Id = new Guid("97a74584-fc02-4609-bd17-079a1b3372f5"),
                            Agility = 20,
                            Category = 2,
                            Intelligence = 10,
                            Name = "Iron Gauntlets",
                            Price = 40,
                            Strength = 50
                        },
                        new
                        {
                            Id = new Guid("1f2e6fa5-3cd4-4a7a-9f32-ea8fa7da0489"),
                            Agility = 100,
                            Category = 2,
                            Intelligence = 5,
                            Name = "Leather Gloves",
                            Price = 25,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("81a04d0a-d976-4c51-8d76-bd6778298648"),
                            Agility = 60,
                            Category = 2,
                            Intelligence = 175,
                            Name = "Enchanted Gloves",
                            Price = 90,
                            Strength = 8
                        },
                        new
                        {
                            Id = new Guid("2fb77191-bb5b-441c-b85f-2fe468f17f40"),
                            Agility = 30,
                            Category = 3,
                            Intelligence = -100,
                            Name = "Steel Boots",
                            Price = 50,
                            Strength = 40
                        },
                        new
                        {
                            Id = new Guid("1398b36d-9036-4725-a8cc-3335423b4df4"),
                            Agility = 200,
                            Category = 3,
                            Intelligence = 30,
                            Name = "Ninja Sandals",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("eaa1cc35-7910-4e21-830d-984e8cd31cf1"),
                            Agility = 250,
                            Category = 3,
                            Intelligence = 80,
                            Name = "Mage Slippers",
                            Price = 70,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("a4404053-2bca-4ff4-9f48-f0256a87f528"),
                            Agility = 50,
                            Category = 4,
                            Intelligence = -20,
                            Name = "Ring of Strength",
                            Price = 200,
                            Strength = 100
                        },
                        new
                        {
                            Id = new Guid("fff219b3-95c6-4c1c-bcdd-f4c51786ae57"),
                            Agility = -25,
                            Category = 4,
                            Intelligence = 200,
                            Name = "Ring of Intelligence",
                            Price = 180,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("62b1e79f-e5fd-4153-941b-d0ca0711d995"),
                            Agility = 300,
                            Category = 4,
                            Intelligence = -50,
                            Name = "Ring of Agility",
                            Price = 160,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("c42f836e-8134-415d-b2e3-ef2335bc7480"),
                            Agility = 40,
                            Category = 5,
                            Intelligence = 60,
                            Name = "Amulet of Power",
                            Price = 250,
                            Strength = 90
                        },
                        new
                        {
                            Id = new Guid("f511fade-ee53-46f9-ae24-7b42f73f3786"),
                            Agility = 75,
                            Category = 5,
                            Intelligence = 180,
                            Name = "Mystic Necklace",
                            Price = 220,
                            Strength = 20
                        },
                        new
                        {
                            Id = new Guid("f0209de1-d8c9-4dc4-ac6f-e7f5e91a6510"),
                            Agility = 280,
                            Category = 5,
                            Intelligence = 70,
                            Name = "Pendant of Speed",
                            Price = 190,
                            Strength = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87990ca7-9b6c-4dba-b62b-4493c1410ea3"),
                            EquipmentId = new Guid("b8337871-8051-48a7-8dc0-6ac15d7fbfd1"),
                            NinjaId = new Guid("7fe489cd-fbcd-41b1-8abf-3fc6661dfdd0"),
                            SlotCategory = 0
                        },
                        new
                        {
                            Id = new Guid("6a80dea8-5cde-4ae0-ac75-af5e7ce742e2"),
                            EquipmentId = new Guid("890c908d-345b-4604-97b7-f36b627dce1c"),
                            NinjaId = new Guid("7fe489cd-fbcd-41b1-8abf-3fc6661dfdd0"),
                            SlotCategory = 1
                        },
                        new
                        {
                            Id = new Guid("60496f77-be0b-44ad-94dd-dd43c2632534"),
                            EquipmentId = new Guid("97a74584-fc02-4609-bd17-079a1b3372f5"),
                            NinjaId = new Guid("7fe489cd-fbcd-41b1-8abf-3fc6661dfdd0"),
                            SlotCategory = 2
                        },
                        new
                        {
                            Id = new Guid("5032dd77-15ad-49d9-9487-931bb3cf13db"),
                            EquipmentId = new Guid("5c9849f7-3ea8-4acb-8903-c97f92d760b9"),
                            NinjaId = new Guid("a74fccc6-8e66-43be-89a8-2f7f3f13a3aa"),
                            SlotCategory = 0
                        },
                        new
                        {
                            Id = new Guid("ea0c59a0-78ce-41bf-84ab-02f0fbfdbdb4"),
                            EquipmentId = new Guid("c61006de-2573-415d-abac-c8a1778224e0"),
                            NinjaId = new Guid("a74fccc6-8e66-43be-89a8-2f7f3f13a3aa"),
                            SlotCategory = 1
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fe489cd-fbcd-41b1-8abf-3fc6661dfdd0"),
                            Gold = 2000,
                            Name = "Shadowstrike Kenji"
                        },
                        new
                        {
                            Id = new Guid("a74fccc6-8e66-43be-89a8-2f7f3f13a3aa"),
                            Gold = 500,
                            Name = "Crimson Whisper"
                        },
                        new
                        {
                            Id = new Guid("5c12aa70-5ad1-4b64-be27-ee0d89fa7bcb"),
                            Gold = 2000,
                            Name = "Nightwind Taro"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
