// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.Database;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20241031205607_fixForManyToManyInventory")]
    partial class fixForManyToManyInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("967bf2a8-85fe-4d3f-aeb5-9abaae66743b"),
                            Agility = 10,
                            Category = 0,
                            Intelligence = 20,
                            Name = "Steel Helmet",
                            Price = 50,
                            Strength = 30
                        },
                        new
                        {
                            Id = new Guid("3a4d0f45-48d6-4abf-ac3a-644073a37e7a"),
                            Agility = 50,
                            Category = 0,
                            Intelligence = -50,
                            Name = "Leather Hood",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("3b5c8b6f-e3f4-4d55-bc1a-690b26e06d98"),
                            Agility = 30,
                            Category = 0,
                            Intelligence = 150,
                            Name = "Mystic Crown",
                            Price = 100,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("f8c60582-5428-4500-b26e-1916aa90d4ac"),
                            Agility = -10,
                            Category = 1,
                            Intelligence = 40,
                            Name = "Chainmail Armor",
                            Price = 120,
                            Strength = 80
                        },
                        new
                        {
                            Id = new Guid("31f562ee-b6fe-466d-8678-3716761a7532"),
                            Agility = 70,
                            Category = 1,
                            Intelligence = 100,
                            Name = "Silk Robe",
                            Price = 80,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("5fddc917-0edc-402d-8dad-c367f36bf969"),
                            Agility = 90,
                            Category = 1,
                            Intelligence = -30,
                            Name = "Battle Vest",
                            Price = 60,
                            Strength = 60
                        },
                        new
                        {
                            Id = new Guid("c525d662-3828-411a-8d07-cf84d01b8763"),
                            Agility = 20,
                            Category = 2,
                            Intelligence = 10,
                            Name = "Iron Gauntlets",
                            Price = 40,
                            Strength = 50
                        },
                        new
                        {
                            Id = new Guid("692c85f9-2f3d-402c-80ff-7e7d4a883b46"),
                            Agility = 100,
                            Category = 2,
                            Intelligence = 5,
                            Name = "Leather Gloves",
                            Price = 25,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("e1a2c576-e89e-452f-a863-c295aea230f5"),
                            Agility = 60,
                            Category = 2,
                            Intelligence = 175,
                            Name = "Enchanted Gloves",
                            Price = 90,
                            Strength = 8
                        },
                        new
                        {
                            Id = new Guid("7e64ba8f-60fb-4f45-b336-35d492eadf37"),
                            Agility = 30,
                            Category = 3,
                            Intelligence = -100,
                            Name = "Steel Boots",
                            Price = 50,
                            Strength = 40
                        },
                        new
                        {
                            Id = new Guid("8b35217f-940e-498f-8826-f1603ccab4f1"),
                            Agility = 200,
                            Category = 3,
                            Intelligence = 30,
                            Name = "Ninja Sandals",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("6c4371e8-aef1-4f35-a284-e07266b27dc8"),
                            Agility = 250,
                            Category = 3,
                            Intelligence = 80,
                            Name = "Mage Slippers",
                            Price = 70,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("d6605cc5-b5a1-408d-b2d9-4c6d9323ec45"),
                            Agility = 50,
                            Category = 4,
                            Intelligence = -20,
                            Name = "Ring of Strength",
                            Price = 200,
                            Strength = 100
                        },
                        new
                        {
                            Id = new Guid("81246263-02ba-42fa-946d-19e5782572bc"),
                            Agility = -25,
                            Category = 4,
                            Intelligence = 200,
                            Name = "Ring of Intelligence",
                            Price = 180,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("4daa48b3-b218-4d90-864c-7995201be170"),
                            Agility = 300,
                            Category = 4,
                            Intelligence = -50,
                            Name = "Ring of Agility",
                            Price = 160,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("ca704078-b6f2-44e9-bf86-8d1c6d3dee27"),
                            Agility = 40,
                            Category = 5,
                            Intelligence = 60,
                            Name = "Amulet of Power",
                            Price = 250,
                            Strength = 90
                        },
                        new
                        {
                            Id = new Guid("241e3387-35f6-489f-b2c0-0ece0a335a2a"),
                            Agility = 75,
                            Category = 5,
                            Intelligence = 180,
                            Name = "Mystic Necklace",
                            Price = 220,
                            Strength = 20
                        },
                        new
                        {
                            Id = new Guid("e28b4170-e371-4a6d-919d-379bdbbb3728"),
                            Agility = 280,
                            Category = 5,
                            Intelligence = 70,
                            Name = "Pendant of Speed",
                            Price = 190,
                            Strength = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af1c5735-da07-43cc-9f00-48704c40ab01"),
                            EquipmentId = new Guid("967bf2a8-85fe-4d3f-aeb5-9abaae66743b"),
                            NinjaId = new Guid("a6731d1b-88f0-4e74-b851-3fd1138f0bf6")
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6731d1b-88f0-4e74-b851-3fd1138f0bf6"),
                            Gold = 2000,
                            Name = "Shadowstrike Kenji"
                        },
                        new
                        {
                            Id = new Guid("ff2ab46c-af86-4e9f-ac71-05a1592839c9"),
                            Gold = 500,
                            Name = "Crimson Whisper"
                        },
                        new
                        {
                            Id = new Guid("08ef212c-ef31-4901-aabd-4660cb5b52b4"),
                            Gold = 2000,
                            Name = "Nightwind Taro"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
