// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.Database;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20241031185549_UpdatedInventoryItem")]
    partial class UpdatedInventoryItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d29ef4aa-7faa-4d6f-b983-7b10e85244ce"),
                            Agility = 10,
                            Category = 0,
                            Intelligence = 20,
                            Name = "Steel Helmet",
                            Price = 50,
                            Strength = 30
                        },
                        new
                        {
                            Id = new Guid("46f0b7a1-90b0-4fe8-974d-6921a505de68"),
                            Agility = 50,
                            Category = 0,
                            Intelligence = -50,
                            Name = "Leather Hood",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("fdf5a04d-fcf3-499b-827a-d5008203c047"),
                            Agility = 30,
                            Category = 0,
                            Intelligence = 150,
                            Name = "Mystic Crown",
                            Price = 100,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("b4e9d474-196f-47f5-a83c-d7218288c929"),
                            Agility = -10,
                            Category = 1,
                            Intelligence = 40,
                            Name = "Chainmail Armor",
                            Price = 120,
                            Strength = 80
                        },
                        new
                        {
                            Id = new Guid("e1a9e9fe-f314-493a-a45d-6b855449a910"),
                            Agility = 70,
                            Category = 1,
                            Intelligence = 100,
                            Name = "Silk Robe",
                            Price = 80,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("73d4cb7b-2729-4c09-91ab-d7e2b7818451"),
                            Agility = 90,
                            Category = 1,
                            Intelligence = -30,
                            Name = "Battle Vest",
                            Price = 60,
                            Strength = 60
                        },
                        new
                        {
                            Id = new Guid("2d60fbe8-6eae-4a34-9df9-b31990c4a873"),
                            Agility = 20,
                            Category = 2,
                            Intelligence = 10,
                            Name = "Iron Gauntlets",
                            Price = 40,
                            Strength = 50
                        },
                        new
                        {
                            Id = new Guid("72c9d37d-cf5c-44c1-b394-04a8dd410440"),
                            Agility = 100,
                            Category = 2,
                            Intelligence = 5,
                            Name = "Leather Gloves",
                            Price = 25,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("5e196fcc-af8d-45e6-9a94-b8c5e8131387"),
                            Agility = 60,
                            Category = 2,
                            Intelligence = 175,
                            Name = "Enchanted Gloves",
                            Price = 90,
                            Strength = 8
                        },
                        new
                        {
                            Id = new Guid("8d54ce4b-569a-4903-bed9-b9f5711733c4"),
                            Agility = 30,
                            Category = 3,
                            Intelligence = -100,
                            Name = "Steel Boots",
                            Price = 50,
                            Strength = 40
                        },
                        new
                        {
                            Id = new Guid("f2896bdf-4763-49bf-9460-9016ee1ddcc5"),
                            Agility = 200,
                            Category = 3,
                            Intelligence = 30,
                            Name = "Ninja Sandals",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("fd17aaba-6cf0-48a6-a3ce-3167892267ee"),
                            Agility = 250,
                            Category = 3,
                            Intelligence = 80,
                            Name = "Mage Slippers",
                            Price = 70,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("6e00cd5c-e74b-4860-aaae-5dd59f368be8"),
                            Agility = 50,
                            Category = 4,
                            Intelligence = -20,
                            Name = "Ring of Strength",
                            Price = 200,
                            Strength = 100
                        },
                        new
                        {
                            Id = new Guid("d3630843-fd37-4900-8ce2-0401dae8639d"),
                            Agility = -25,
                            Category = 4,
                            Intelligence = 200,
                            Name = "Ring of Intelligence",
                            Price = 180,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("181d6be2-e017-48d0-a328-6998051e7c59"),
                            Agility = 300,
                            Category = 4,
                            Intelligence = -50,
                            Name = "Ring of Agility",
                            Price = 160,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("1c425fd4-c50c-48c4-8511-066705141c61"),
                            Agility = 40,
                            Category = 5,
                            Intelligence = 60,
                            Name = "Amulet of Power",
                            Price = 250,
                            Strength = 90
                        },
                        new
                        {
                            Id = new Guid("42eff9c7-8694-4cdb-9e57-7f82301e57a5"),
                            Agility = 75,
                            Category = 5,
                            Intelligence = 180,
                            Name = "Mystic Necklace",
                            Price = 220,
                            Strength = 20
                        },
                        new
                        {
                            Id = new Guid("d7ea24b5-86c3-48d3-8b44-41f112f898b6"),
                            Agility = 280,
                            Category = 5,
                            Intelligence = 70,
                            Name = "Pendant of Speed",
                            Price = 190,
                            Strength = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56c43a75-72ed-4378-9607-10ba888751f3"),
                            EquipmentId = new Guid("d29ef4aa-7faa-4d6f-b983-7b10e85244ce"),
                            NinjaId = new Guid("2f42f382-2d81-430d-bc6b-ccf91586887c"),
                            SlotCategory = 0
                        },
                        new
                        {
                            Id = new Guid("b2c579d0-8174-489d-8f71-c5b169e528d7"),
                            EquipmentId = new Guid("b4e9d474-196f-47f5-a83c-d7218288c929"),
                            NinjaId = new Guid("2f42f382-2d81-430d-bc6b-ccf91586887c"),
                            SlotCategory = 1
                        },
                        new
                        {
                            Id = new Guid("0bd2c676-644a-4f3d-86ec-d2527f6f1632"),
                            EquipmentId = new Guid("2d60fbe8-6eae-4a34-9df9-b31990c4a873"),
                            NinjaId = new Guid("2f42f382-2d81-430d-bc6b-ccf91586887c"),
                            SlotCategory = 2
                        },
                        new
                        {
                            Id = new Guid("427f75ed-1f59-4a67-aed7-1440f62e35a9"),
                            EquipmentId = new Guid("46f0b7a1-90b0-4fe8-974d-6921a505de68"),
                            NinjaId = new Guid("64426b12-e2a6-4d99-9543-f1254682f5e3"),
                            SlotCategory = 0
                        },
                        new
                        {
                            Id = new Guid("413c0b24-684b-4d64-a908-c387b110c03b"),
                            EquipmentId = new Guid("e1a9e9fe-f314-493a-a45d-6b855449a910"),
                            NinjaId = new Guid("64426b12-e2a6-4d99-9543-f1254682f5e3"),
                            SlotCategory = 1
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f42f382-2d81-430d-bc6b-ccf91586887c"),
                            Gold = 2000,
                            Name = "Shadowstrike Kenji"
                        },
                        new
                        {
                            Id = new Guid("64426b12-e2a6-4d99-9543-f1254682f5e3"),
                            Gold = 500,
                            Name = "Crimson Whisper"
                        },
                        new
                        {
                            Id = new Guid("39f7717a-f353-4bdb-af0f-46b217a0da8c"),
                            Gold = 2000,
                            Name = "Nightwind Taro"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
