// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.Database;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20241103145311_newOrdersSeedData")]
    partial class newOrdersSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8348abe7-b2d9-4ae5-9d68-a25ecbcb51c3"),
                            Agility = 10,
                            Category = 0,
                            Intelligence = 20,
                            Name = "Steel Helmet",
                            Price = 50,
                            Strength = 30
                        },
                        new
                        {
                            Id = new Guid("5ec8e393-7f7c-4fbf-bdbd-2b9c577951b3"),
                            Agility = 50,
                            Category = 0,
                            Intelligence = -50,
                            Name = "Leather Hood",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("6df100d7-dfc4-4e9e-a18a-81d74619052c"),
                            Agility = 30,
                            Category = 0,
                            Intelligence = 150,
                            Name = "Mystic Crown",
                            Price = 100,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("f27185f3-7d8a-4590-83d9-ab00f7d6c001"),
                            Agility = -10,
                            Category = 1,
                            Intelligence = 40,
                            Name = "Chainmail Armor",
                            Price = 120,
                            Strength = 80
                        },
                        new
                        {
                            Id = new Guid("3775f52e-4f7c-4059-a1a3-d761a4473225"),
                            Agility = 70,
                            Category = 1,
                            Intelligence = 100,
                            Name = "Silk Robe",
                            Price = 80,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("c922d2aa-78c3-43e5-9b43-52b74aaf7574"),
                            Agility = 90,
                            Category = 1,
                            Intelligence = -30,
                            Name = "Battle Vest",
                            Price = 60,
                            Strength = 60
                        },
                        new
                        {
                            Id = new Guid("6245bae0-4693-4aa1-8d64-2b9d45270f8b"),
                            Agility = 20,
                            Category = 2,
                            Intelligence = 10,
                            Name = "Iron Gauntlets",
                            Price = 40,
                            Strength = 50
                        },
                        new
                        {
                            Id = new Guid("17320398-1ef4-4818-8599-9a9409b52158"),
                            Agility = 100,
                            Category = 2,
                            Intelligence = 5,
                            Name = "Leather Gloves",
                            Price = 25,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("f79c44cc-656c-4f6f-94c7-b00b2759c9ec"),
                            Agility = 60,
                            Category = 2,
                            Intelligence = 175,
                            Name = "Enchanted Gloves",
                            Price = 90,
                            Strength = 8
                        },
                        new
                        {
                            Id = new Guid("4a444908-ed4e-4f40-bf57-9bb20b124bc2"),
                            Agility = 30,
                            Category = 3,
                            Intelligence = -100,
                            Name = "Steel Boots",
                            Price = 50,
                            Strength = 40
                        },
                        new
                        {
                            Id = new Guid("2898a80b-6936-4d9d-9c60-740102d1409c"),
                            Agility = 200,
                            Category = 3,
                            Intelligence = 30,
                            Name = "Ninja Sandals",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("96abae21-086c-4ca0-85bb-cd8a76709946"),
                            Agility = 250,
                            Category = 3,
                            Intelligence = 80,
                            Name = "Mage Slippers",
                            Price = 70,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("776cf20c-d7e6-4b73-afbf-e6c410659d0b"),
                            Agility = 50,
                            Category = 4,
                            Intelligence = -20,
                            Name = "Ring of Strength",
                            Price = 200,
                            Strength = 100
                        },
                        new
                        {
                            Id = new Guid("57351fec-348c-4c75-b077-9b0d58d1dc55"),
                            Agility = -25,
                            Category = 4,
                            Intelligence = 200,
                            Name = "Ring of Intelligence",
                            Price = 180,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("2546f7f2-c3e6-48bd-98ef-d81ffc42152d"),
                            Agility = 300,
                            Category = 4,
                            Intelligence = -50,
                            Name = "Ring of Agility",
                            Price = 160,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("a68cfc77-ad39-4568-9da2-f1cfcd4cc2c3"),
                            Agility = 40,
                            Category = 5,
                            Intelligence = 60,
                            Name = "Amulet of Power",
                            Price = 250,
                            Strength = 90
                        },
                        new
                        {
                            Id = new Guid("49527477-41af-4de9-9df6-f80dff12acd9"),
                            Agility = 75,
                            Category = 5,
                            Intelligence = 180,
                            Name = "Mystic Necklace",
                            Price = 220,
                            Strength = 20
                        },
                        new
                        {
                            Id = new Guid("dea6f0b2-511c-4073-a146-9ade47b0fc5d"),
                            Agility = 280,
                            Category = 5,
                            Intelligence = 70,
                            Name = "Pendant of Speed",
                            Price = 190,
                            Strength = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b31e5d23-f338-4e68-bfd6-88f70ae6393f"),
                            EquipmentId = new Guid("8348abe7-b2d9-4ae5-9d68-a25ecbcb51c3"),
                            NinjaId = new Guid("7be98e5f-e8de-492e-837b-581bb493630f")
                        },
                        new
                        {
                            Id = new Guid("0fdb0f79-7554-490b-9a0c-904fc58ed891"),
                            EquipmentId = new Guid("f27185f3-7d8a-4590-83d9-ab00f7d6c001"),
                            NinjaId = new Guid("7be98e5f-e8de-492e-837b-581bb493630f")
                        },
                        new
                        {
                            Id = new Guid("e37432b0-b8dc-4064-85f0-b3746e82e0db"),
                            EquipmentId = new Guid("6245bae0-4693-4aa1-8d64-2b9d45270f8b"),
                            NinjaId = new Guid("7be98e5f-e8de-492e-837b-581bb493630f")
                        },
                        new
                        {
                            Id = new Guid("a8c5c4e2-7024-46ae-9218-615b9ae203e6"),
                            EquipmentId = new Guid("5ec8e393-7f7c-4fbf-bdbd-2b9c577951b3"),
                            NinjaId = new Guid("835e4cf7-f75f-45ec-812e-620039ba0914")
                        },
                        new
                        {
                            Id = new Guid("c443b8b3-5ced-4b2c-b57f-bd916e6517a2"),
                            EquipmentId = new Guid("3775f52e-4f7c-4059-a1a3-d761a4473225"),
                            NinjaId = new Guid("835e4cf7-f75f-45ec-812e-620039ba0914")
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7be98e5f-e8de-492e-837b-581bb493630f"),
                            Gold = 2000,
                            Name = "Shadowstrike Kenji"
                        },
                        new
                        {
                            Id = new Guid("835e4cf7-f75f-45ec-812e-620039ba0914"),
                            Gold = 500,
                            Name = "Crimson Whisper"
                        },
                        new
                        {
                            Id = new Guid("e50510ee-8f0d-437f-b0ae-af3f12f5560a"),
                            Gold = 2000,
                            Name = "Nightwind Taro"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a14a2979-7306-45ed-af75-7114612addcb"),
                            EquipmentId = new Guid("8348abe7-b2d9-4ae5-9d68-a25ecbcb51c3"),
                            NinjaId = new Guid("7be98e5f-e8de-492e-837b-581bb493630f"),
                            Price = 50
                        },
                        new
                        {
                            Id = new Guid("8f1bf675-ae4b-420a-a58c-4f884e00f69d"),
                            EquipmentId = new Guid("f27185f3-7d8a-4590-83d9-ab00f7d6c001"),
                            NinjaId = new Guid("7be98e5f-e8de-492e-837b-581bb493630f"),
                            Price = 120
                        },
                        new
                        {
                            Id = new Guid("4e6bf2ca-df75-4cc0-8b88-8b5f70253b67"),
                            EquipmentId = new Guid("6245bae0-4693-4aa1-8d64-2b9d45270f8b"),
                            NinjaId = new Guid("7be98e5f-e8de-492e-837b-581bb493630f"),
                            Price = 40
                        },
                        new
                        {
                            Id = new Guid("6941bef1-1d89-4f7a-ac5b-5a81aa5f6f38"),
                            EquipmentId = new Guid("5ec8e393-7f7c-4fbf-bdbd-2b9c577951b3"),
                            NinjaId = new Guid("835e4cf7-f75f-45ec-812e-620039ba0914"),
                            Price = 30
                        },
                        new
                        {
                            Id = new Guid("ae29b7ce-4698-41f2-952c-d651358bf6cd"),
                            EquipmentId = new Guid("3775f52e-4f7c-4059-a1a3-d761a4473225"),
                            NinjaId = new Guid("835e4cf7-f75f-45ec-812e-620039ba0914"),
                            Price = 80
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
