// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.Database;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20241031202452_updatedSeedData")]
    partial class updatedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76d13a7a-0bfd-4830-8633-e905c42636cb"),
                            Agility = 10,
                            Category = 0,
                            Intelligence = 20,
                            Name = "Steel Helmet",
                            Price = 50,
                            Strength = 30
                        },
                        new
                        {
                            Id = new Guid("8fcbb75e-15a0-47c3-a41e-f32ab5ea2772"),
                            Agility = 50,
                            Category = 0,
                            Intelligence = -50,
                            Name = "Leather Hood",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("59f9994e-1693-4362-a937-6990de3d95fd"),
                            Agility = 30,
                            Category = 0,
                            Intelligence = 150,
                            Name = "Mystic Crown",
                            Price = 100,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("86be4da2-2736-40d0-8822-712fe43e4150"),
                            Agility = -10,
                            Category = 1,
                            Intelligence = 40,
                            Name = "Chainmail Armor",
                            Price = 120,
                            Strength = 80
                        },
                        new
                        {
                            Id = new Guid("ce6b3185-a903-4af0-b302-8b596aaa5e2f"),
                            Agility = 70,
                            Category = 1,
                            Intelligence = 100,
                            Name = "Silk Robe",
                            Price = 80,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("c1629c2f-1f52-4d2d-a6ca-73b32caa516f"),
                            Agility = 90,
                            Category = 1,
                            Intelligence = -30,
                            Name = "Battle Vest",
                            Price = 60,
                            Strength = 60
                        },
                        new
                        {
                            Id = new Guid("87d92e5f-5fdd-4584-a9ec-2497bfd2741f"),
                            Agility = 20,
                            Category = 2,
                            Intelligence = 10,
                            Name = "Iron Gauntlets",
                            Price = 40,
                            Strength = 50
                        },
                        new
                        {
                            Id = new Guid("5bef76c8-3ca8-4b12-921c-3cde5fd5b25e"),
                            Agility = 100,
                            Category = 2,
                            Intelligence = 5,
                            Name = "Leather Gloves",
                            Price = 25,
                            Strength = 15
                        },
                        new
                        {
                            Id = new Guid("bd568a85-9bc3-4817-af3a-3f2333a9f884"),
                            Agility = 60,
                            Category = 2,
                            Intelligence = 175,
                            Name = "Enchanted Gloves",
                            Price = 90,
                            Strength = 8
                        },
                        new
                        {
                            Id = new Guid("16d3df9f-8c95-493b-83bf-30f8814cd292"),
                            Agility = 30,
                            Category = 3,
                            Intelligence = -100,
                            Name = "Steel Boots",
                            Price = 50,
                            Strength = 40
                        },
                        new
                        {
                            Id = new Guid("af33fa1a-5213-498d-b112-8b5326332480"),
                            Agility = 200,
                            Category = 3,
                            Intelligence = 30,
                            Name = "Ninja Sandals",
                            Price = 30,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("597175c5-f705-466e-90e7-59c6a7a552fe"),
                            Agility = 250,
                            Category = 3,
                            Intelligence = 80,
                            Name = "Mage Slippers",
                            Price = 70,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("cf393a15-1a25-4685-a9ac-9834275b7425"),
                            Agility = 50,
                            Category = 4,
                            Intelligence = -20,
                            Name = "Ring of Strength",
                            Price = 200,
                            Strength = 100
                        },
                        new
                        {
                            Id = new Guid("1c318831-e602-4736-9501-3b7955a61ac4"),
                            Agility = -25,
                            Category = 4,
                            Intelligence = 200,
                            Name = "Ring of Intelligence",
                            Price = 180,
                            Strength = 5
                        },
                        new
                        {
                            Id = new Guid("40836e54-bcdb-4992-a1f4-f680838f7d97"),
                            Agility = 300,
                            Category = 4,
                            Intelligence = -50,
                            Name = "Ring of Agility",
                            Price = 160,
                            Strength = 10
                        },
                        new
                        {
                            Id = new Guid("1839c1d1-ba91-470c-984c-b0be7c2e6749"),
                            Agility = 40,
                            Category = 5,
                            Intelligence = 60,
                            Name = "Amulet of Power",
                            Price = 250,
                            Strength = 90
                        },
                        new
                        {
                            Id = new Guid("3a3217e4-7fc5-44b9-ab78-7ba1d6f30059"),
                            Agility = 75,
                            Category = 5,
                            Intelligence = 180,
                            Name = "Mystic Necklace",
                            Price = 220,
                            Strength = 20
                        },
                        new
                        {
                            Id = new Guid("56964eec-c901-4ff5-a064-5d2d5202127c"),
                            Agility = 280,
                            Category = 5,
                            Intelligence = 70,
                            Name = "Pendant of Speed",
                            Price = 190,
                            Strength = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3dc9f57-3d72-4a66-adb5-84d26343742e"),
                            Gold = 2000,
                            Name = "Shadowstrike Kenji"
                        },
                        new
                        {
                            Id = new Guid("9561f95c-7591-4b7d-af9c-247514c290ed"),
                            Gold = 500,
                            Name = "Crimson Whisper"
                        },
                        new
                        {
                            Id = new Guid("348d718c-e7e0-42c9-8daa-66d0f67ee7b8"),
                            Gold = 2000,
                            Name = "Nightwind Taro"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NinjaApp.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Order", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
